import { StyleSheet } from 'react-native';
import { palette } from '../theme/palette';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: palette.bg },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 32 },
  orbTop: { position: 'absolute', top: -70, right: -30, width: 220, height: 220, borderRadius: 110, backgroundColor: 'rgba(255,122,89,0.2)' },
  orbLeft: { position: 'absolute', top: 240, left: -90, width: 240, height: 240, borderRadius: 120, backgroundColor: 'rgba(105,200,255,0.12)' },
  orbBottom: { position: 'absolute', bottom: -110, right: -70, width: 260, height: 260, borderRadius: 130, backgroundColor: 'rgba(89,212,168,0.12)' },
  loadingEyebrow: { color: palette.sand, fontSize: 11, letterSpacing: 2, textTransform: 'uppercase', marginBottom: 10 },
  loadingTitle: { color: palette.text, fontSize: 44, fontWeight: '800', marginBottom: 10 },
  loadingText: { color: palette.muted, fontSize: 15, lineHeight: 22, textAlign: 'center' },
  authScreen: { padding: 22, paddingTop: 32, paddingBottom: 36, gap: 24 },
  authCopy: { gap: 10, marginTop: 18 },
  authEyebrow: { color: palette.sand, fontSize: 11, textTransform: 'uppercase', letterSpacing: 2 },
  authTitle: { color: palette.text, fontSize: 42, lineHeight: 44, fontWeight: '800', maxWidth: 320 },
  authBody: { color: palette.muted, fontSize: 16, lineHeight: 24, maxWidth: 340 },
  authStats: { flexDirection: 'row', gap: 10 },
  authStat: { flex: 1, backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 22, padding: 16, borderWidth: 1, borderColor: palette.line },
  authStatValue: { color: palette.text, fontSize: 20, fontWeight: '800', marginBottom: 6 },
  authStatLabel: { color: palette.muted, fontSize: 12, textTransform: 'uppercase', letterSpacing: 1 },
  authCard: { backgroundColor: 'rgba(17,26,47,0.92)', borderRadius: 28, padding: 22, borderWidth: 1, borderColor: palette.line, gap: 14 },
  authCardEyebrow: { color: palette.sky, fontSize: 12, textTransform: 'uppercase', letterSpacing: 1.6 },
  authCardTitle: { color: palette.text, fontSize: 28, fontWeight: '800', marginBottom: 4 },
  authPrimary: { backgroundColor: palette.coral, borderRadius: 20, paddingVertical: 16, alignItems: 'center', marginTop: 4 },
  authPrimaryText: { color: palette.bg, fontSize: 15, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1.2 },
  authSwitch: { color: palette.sand, textAlign: 'center', fontSize: 14, lineHeight: 20, marginTop: 4 },
  appShell: { flex: 1, paddingHorizontal: 18, paddingTop: 8, paddingBottom: 18 },
  appHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18 },
  appDate: { color: palette.muted, fontSize: 13, marginBottom: 4 },
  appTitle: { color: palette.text, fontSize: 30, fontWeight: '800' },
  statusPill: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.06)', borderWidth: 1, borderColor: palette.line },
  statusDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: palette.mint },
  statusText: { color: palette.text, fontSize: 13, fontWeight: '700' },
  content: { flex: 1 },
  screenContent: { paddingBottom: 24 },
  sectionHeader: { marginBottom: 12, gap: 4 },
  sectionEyebrow: { color: palette.sky, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1.8 },
  sectionTitle: { color: palette.text, fontSize: 24, fontWeight: '800' },
  sectionBody: { color: palette.muted, fontSize: 14, lineHeight: 20 },
  hero: { backgroundColor: 'rgba(17,26,47,0.92)', borderRadius: 30, padding: 22, borderWidth: 1, borderColor: palette.line, marginBottom: 18 },
  heroRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 16, marginBottom: 16 },
  heroCopy: { flex: 1 },
  heroEyebrow: { color: palette.sand, fontSize: 11, textTransform: 'uppercase', letterSpacing: 2, marginBottom: 8 },
  heroTitle: { color: palette.text, fontSize: 32, lineHeight: 35, fontWeight: '800' },
  streakBadge: { backgroundColor: palette.panelAlt, borderRadius: 22, paddingHorizontal: 16, paddingVertical: 12, alignItems: 'center', minWidth: 82 },
  streakLabel: { color: palette.muted, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1.4, marginBottom: 3 },
  streakValue: { color: palette.sand, fontSize: 28, fontWeight: '800' },
  heroText: { color: palette.muted, fontSize: 15, lineHeight: 22, marginBottom: 18 },
  metricBar: { flexDirection: 'row', backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 20, paddingVertical: 14, borderWidth: 1, borderColor: 'rgba(255,255,255,0.06)' },
  metricItem: { flex: 1, alignItems: 'center' },
  metricItemDivider: { borderRightWidth: 1, borderRightColor: 'rgba(255,255,255,0.08)' },
  metricValue: { color: palette.text, fontSize: 22, fontWeight: '800', marginBottom: 3 },
  metricLabel: { color: palette.muted, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1 },
  cardRow: { gap: 12, paddingBottom: 10 },
  highlightCard: { width: 172, borderRadius: 24, padding: 18, backgroundColor: 'rgba(17,26,47,0.92)', borderWidth: 1, borderColor: palette.line },
  highlightAccent: { width: 34, height: 6, borderRadius: 999, marginBottom: 16 },
  highlightTitle: { color: palette.muted, fontSize: 12, textTransform: 'uppercase', letterSpacing: 1.3, marginBottom: 10 },
  highlightValue: { color: palette.text, fontSize: 34, fontWeight: '800', marginBottom: 8 },
  highlightBody: { color: palette.muted, fontSize: 13, lineHeight: 18 },
  panel: { backgroundColor: 'rgba(17,26,47,0.92)', borderRadius: 26, padding: 20, borderWidth: 1, borderColor: palette.line, marginBottom: 16, gap: 14 },
  panelRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  panelTitle: { color: palette.text, fontSize: 18, fontWeight: '700' },
  panelMeta: { color: palette.sand, fontSize: 14, fontWeight: '700' },
  goalHeader: { flexDirection: 'row', alignItems: 'flex-start', gap: 12 },
  goalHeaderTitle: { flex: 1, color: palette.text, fontSize: 18, lineHeight: 24, fontWeight: '800' },
  goalHeaderPill: {
    alignSelf: 'flex-start',
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 7,
    backgroundColor: 'rgba(255,228,187,0.1)',
    borderWidth: 1,
    borderColor: 'rgba(255,228,187,0.2)',
  },
  goalHeaderPillText: { color: palette.sand, fontSize: 13, fontWeight: '800' },
  progressTrack: { height: 12, borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.08)', overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 999, backgroundColor: palette.sky },
  waterButtons: { flexDirection: 'row', gap: 10 },
  waterButton: { flex: 1, borderRadius: 16, paddingVertical: 12, alignItems: 'center', backgroundColor: palette.panelAlt },
  waterButtonText: { color: palette.text, fontSize: 13, fontWeight: '700' },
  dualRow: { flexDirection: 'row', gap: 12, marginBottom: 18 },
  actionCard: { flex: 1, borderRadius: 24, padding: 18, minHeight: 142, justifyContent: 'space-between', borderWidth: 1, borderColor: palette.line },
  actionWarm: { backgroundColor: 'rgba(255,122,89,0.14)' },
  actionCool: { backgroundColor: 'rgba(89,212,168,0.14)' },
  actionKicker: { color: palette.text, fontSize: 13, textTransform: 'uppercase', letterSpacing: 1.5 },
  actionTitle: { color: palette.text, fontSize: 24, lineHeight: 27, fontWeight: '800' },
  actionBody: { color: palette.muted, fontSize: 13, lineHeight: 18 },
  libraryCard: { width: 186, borderRadius: 24, padding: 18, backgroundColor: 'rgba(17,26,47,0.92)', borderWidth: 1, borderColor: palette.line },
  libraryAccent: { width: 38, height: 8, borderRadius: 999, marginBottom: 16 },
  libraryType: { color: palette.muted, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1.8, marginBottom: 10 },
  libraryName: { color: palette.text, fontSize: 22, lineHeight: 24, fontWeight: '800', marginBottom: 10 },
  libraryMeta: { color: palette.sand, fontSize: 13, marginBottom: 4 },
  listScreen: { flex: 1 },
  primaryButton: { backgroundColor: palette.coral, borderRadius: 20, paddingVertical: 16, alignItems: 'center', marginBottom: 16 },
  primaryButtonText: { color: palette.bg, fontSize: 15, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1.2 },
  listContent: { paddingBottom: 12, gap: 12 },
  entryCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(17,26,47,0.92)', borderRadius: 24, borderWidth: 1, borderColor: palette.line, overflow: 'hidden' },
  entryStripe: { width: 6, alignSelf: 'stretch' },
  entryThumbnail: { width: 64, height: 64, borderRadius: 16, marginLeft: 14 },
  entryMain: { flex: 1, paddingHorizontal: 16, paddingVertical: 16 },
  entryActions: { gap: 8, marginRight: 14 },
  entryTitle: { color: palette.text, fontSize: 18, fontWeight: '700', marginBottom: 6 },
  entryMeta: { color: palette.muted, fontSize: 14, marginBottom: 6 },
  entryDate: { color: palette.sky, fontSize: 12, textTransform: 'uppercase', letterSpacing: 1.2 },
  editButton: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 14, backgroundColor: 'rgba(105,200,255,0.12)' },
  editButtonText: { color: palette.sky, fontSize: 12, fontWeight: '700' },
  removeButton: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 14, backgroundColor: 'rgba(255,157,165,0.12)' },
  removeButtonText: { color: palette.rose, fontSize: 12, fontWeight: '700' },
  emptyCard: { backgroundColor: 'rgba(17,26,47,0.84)', borderRadius: 24, padding: 24, borderWidth: 1, borderColor: palette.line, marginTop: 6 },
  emptyTitle: { color: palette.text, fontSize: 20, fontWeight: '800', marginBottom: 8 },
  emptyBody: { color: palette.muted, fontSize: 14, lineHeight: 21 },
  leaderRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.05)' },
  leaderRank: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: palette.panelAlt },
  leaderRankText: { color: palette.sand, fontSize: 12, fontWeight: '800' },
  leaderAvatar: {
    width: 38,
    height: 38,
    borderRadius: 19,
    backgroundColor: 'rgba(255,255,255,0.06)',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
    borderWidth: 1,
    borderColor: palette.line,
  },
  leaderAvatarImage: { width: '100%', height: '100%' },
  leaderAvatarFallback: { color: palette.text, fontSize: 12, fontWeight: '800' },
  leaderMain: { flex: 1 },
  leaderName: { color: palette.text, fontSize: 15, fontWeight: '700', marginBottom: 3 },
  leaderNameCurrent: { color: palette.sand },
  leaderMeta: { color: palette.muted, fontSize: 12, lineHeight: 18 },
  leaderScore: { color: palette.coral, fontSize: 16, fontWeight: '800' },
  inviteCodeCard: {
    borderRadius: 20,
    padding: 16,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: palette.line,
    gap: 6,
  },
  inviteCodeLabel: { color: palette.muted, fontSize: 12, textTransform: 'uppercase', letterSpacing: 1.4 },
  inviteCodeValue: { color: palette.sand, fontSize: 24, fontWeight: '800', letterSpacing: 1.6 },
  friendList: { gap: 10 },
  friendCard: {
    borderRadius: 20,
    padding: 16,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: palette.line,
    gap: 12,
  },
  friendMain: { gap: 4 },
  friendName: { color: palette.text, fontSize: 17, fontWeight: '700' },
  friendMeta: { color: palette.muted, fontSize: 13, lineHeight: 18 },
  friendActions: { flexDirection: 'row', gap: 10 },
  friendActivateButton: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: 'rgba(89,212,168,0.14)',
  },
  friendActivateText: { color: palette.mint, fontSize: 13, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
  friendRemoveButton: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: 'rgba(255,157,165,0.12)',
  },
  friendRemoveText: { color: palette.rose, fontSize: 13, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
  inviteHint: { color: palette.sand, fontSize: 12, lineHeight: 18 },
  profileHero: { alignItems: 'center', marginBottom: 18 },
  avatarCircle: { width: 94, height: 94, borderRadius: 47, backgroundColor: 'rgba(255,122,89,0.16)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,122,89,0.24)', marginBottom: 16 },
  avatarCircleLarge: {
    width: 108,
    height: 108,
    borderRadius: 54,
    backgroundColor: 'rgba(255,122,89,0.16)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,122,89,0.24)',
    marginBottom: 12,
    overflow: 'hidden',
  },
  avatarCircleImage: { width: '100%', height: '100%' },
  avatarText: { color: palette.text, fontSize: 30, fontWeight: '800' },
  profilePhotoAction: { color: palette.sky, fontSize: 13, fontWeight: '700', marginBottom: 10 },
  avatarFrameBadge: {
    position: 'absolute',
    bottom: 8,
    right: -4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    backgroundColor: 'rgba(11,16,32,0.86)',
    borderWidth: 1,
    borderColor: palette.line,
  },
  avatarFrameBadgeText: { color: palette.sand, fontSize: 10, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
  profileName: { color: palette.text, fontSize: 30, fontWeight: '800', marginBottom: 6 },
  profileEmail: { color: palette.muted, fontSize: 14 },
  scoreRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  scoreCard: { flex: 1, backgroundColor: 'rgba(17,26,47,0.92)', borderRadius: 22, paddingVertical: 20, alignItems: 'center', borderWidth: 1, borderColor: palette.line },
  scoreValue: { color: palette.text, fontSize: 28, fontWeight: '800', marginBottom: 4 },
  scoreLabel: { color: palette.muted, fontSize: 12, textTransform: 'uppercase', letterSpacing: 1.2 },
  profileBody: { color: palette.muted, fontSize: 14, lineHeight: 22 },
  goalChipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  goalChip: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: 'rgba(255,255,255,0.05)',
    borderWidth: 1,
    borderColor: palette.line,
  },
  goalChipActive: { backgroundColor: 'rgba(255,122,89,0.18)', borderColor: 'rgba(255,122,89,0.4)' },
  goalChipText: { color: palette.text, fontSize: 12, fontWeight: '700' },
  goalChipTextActive: { color: palette.sand },
  goalSummaryRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 12, flexWrap: 'wrap' },
  goalSummaryValue: { color: palette.text, fontSize: 16, fontWeight: '800' },
  goalSummaryMeta: { color: palette.sand, fontSize: 12, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1 },
  goalMilestoneHint: { color: palette.sky, fontSize: 12, lineHeight: 18 },
  rewardHero: {
    borderRadius: 20,
    padding: 16,
    backgroundColor: 'rgba(105,200,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(105,200,255,0.18)',
    gap: 6,
  },
  rewardHeroEyebrow: { color: palette.sky, fontSize: 11, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1.4 },
  rewardHeroTitle: { color: palette.text, fontSize: 22, fontWeight: '800' },
  rewardHeroBody: { color: palette.muted, fontSize: 13, lineHeight: 19 },
  rewardHeroMeta: { color: palette.sand, fontSize: 12, fontWeight: '700' },
  rewardPulseAction: { color: palette.sky, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1.1 },
  milestoneCard: {
    borderRadius: 18,
    padding: 16,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: palette.line,
    gap: 8,
  },
  milestoneTitle: { color: palette.text, fontSize: 15, fontWeight: '700' },
  milestoneMeta: { color: palette.muted, fontSize: 13, lineHeight: 18 },
  milestoneReward: { color: palette.sand, fontSize: 12, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1 },
  achievement: { alignSelf: 'flex-start', paddingHorizontal: 14, paddingVertical: 9, borderRadius: 999, backgroundColor: palette.panelAlt, color: palette.sand, fontSize: 12, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1 },
  signOutButton: { backgroundColor: 'rgba(255,157,165,0.14)', borderRadius: 18, paddingVertical: 16, alignItems: 'center' },
  signOutButtonText: { color: palette.rose, fontSize: 15, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
  tabBar: { flexDirection: 'row', gap: 10, padding: 10, borderRadius: 26, backgroundColor: 'rgba(17,26,47,0.94)', borderWidth: 1, borderColor: palette.line, marginTop: 14 },
  tabButton: { flex: 1, borderRadius: 18, paddingVertical: 12, alignItems: 'center', gap: 4 },
  tabButtonActive: { backgroundColor: palette.panelAlt },
  tabCode: { color: palette.muted, fontSize: 10, fontWeight: '700', letterSpacing: 1.4 },
  tabCodeActive: { color: palette.sand },
  tabText: { color: palette.muted, fontSize: 12, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1 },
  tabTextActive: { color: palette.text },
  modalKeyboardWrap: { flex: 1 },
  modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(2,6,14,0.72)' },
  modalSheet: {
    maxHeight: '84%',
    backgroundColor: palette.panel,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    paddingHorizontal: 22,
    paddingTop: 12,
    paddingBottom: 24,
    borderTopWidth: 1,
    borderColor: palette.line,
    gap: 14,
  },
  modalHandle: { alignSelf: 'center', width: 52, height: 5, borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.16)' },
  modalHeaderRow: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: 12 },
  modalHeaderCopy: { flex: 1, gap: 4 },
  modalCloseButton: {
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: 'rgba(255,255,255,0.06)',
    borderWidth: 1,
    borderColor: palette.line,
  },
  modalCloseButtonText: { color: palette.text, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
  modalScroll: { flexGrow: 0 },
  modalScrollContent: { gap: 14, paddingBottom: 8 },
  modalEyebrow: { color: palette.sand, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1.8 },
  modalTitle: { color: palette.text, fontSize: 30, fontWeight: '800' },
  input: { backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 18, paddingHorizontal: 16, paddingVertical: 15, color: palette.text, fontSize: 16, borderWidth: 1, borderColor: palette.line },
  photoPanel: {
    borderRadius: 18,
    padding: 16,
    backgroundColor: 'rgba(255,255,255,0.04)',
    borderWidth: 1,
    borderColor: palette.line,
    gap: 12,
  },
  photoPanelHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  photoPanelTitle: { color: palette.text, fontSize: 16, fontWeight: '700' },
  photoPanelMeta: { color: palette.muted, fontSize: 12, textTransform: 'uppercase', letterSpacing: 1.2 },
  mealPhotoPreview: { width: '100%', height: 180, borderRadius: 18 },
  mealPhotoPlaceholder: {
    height: 120,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: palette.line,
    borderStyle: 'dashed',
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  mealPhotoPlaceholderText: { color: palette.muted, fontSize: 13, lineHeight: 19, textAlign: 'center' },
  photoActionRow: { flexDirection: 'row', gap: 10 },
  photoActionButton: {
    flex: 1,
    borderRadius: 14,
    paddingVertical: 12,
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.06)',
  },
  photoActionButtonText: { color: palette.text, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
  photoAnalyzeButton: { marginBottom: 0 },
  photoAnalyzeButtonDisabled: { opacity: 0.6 },
  photoHintText: { color: palette.sky, fontSize: 12, lineHeight: 18 },
  estimateCard: {
    borderRadius: 18,
    padding: 16,
    backgroundColor: 'rgba(105,200,255,0.08)',
    borderWidth: 1,
    borderColor: 'rgba(105,200,255,0.2)',
    gap: 8,
  },
  estimateEyebrow: { color: palette.sky, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1.4 },
  estimateTitle: { color: palette.text, fontSize: 16, fontWeight: '700' },
  estimateBody: { color: palette.muted, fontSize: 13, lineHeight: 18 },
  estimateButton: {
    alignSelf: 'flex-start',
    borderRadius: 14,
    paddingHorizontal: 14,
    paddingVertical: 10,
    backgroundColor: 'rgba(255,255,255,0.08)',
  },
  estimateButtonText: { color: palette.text, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
  segmentRow: { flexDirection: 'row', gap: 10 },
  segmentButton: { flex: 1, borderRadius: 16, paddingVertical: 13, alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.04)', borderWidth: 1, borderColor: palette.line },
  segmentButtonActive: { backgroundColor: palette.coral, borderColor: palette.coral },
  segmentText: { color: palette.muted, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
  segmentTextActive: { color: palette.bg },
  dualInputRow: { flexDirection: 'row', gap: 12 },
  half: { flex: 1 },
  modalActions: { flexDirection: 'row', gap: 12, marginTop: 4 },
  modalGhost: { flex: 1, borderRadius: 18, paddingVertical: 16, alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.06)' },
  modalGhostText: { color: palette.text, fontSize: 14, fontWeight: '700' },
  modalPrimary: { flex: 1, borderRadius: 18, paddingVertical: 16, alignItems: 'center', backgroundColor: palette.coral },
  modalPrimaryText: { color: palette.bg, fontSize: 14, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
});
