import { StyleSheet } from 'react-native';
import { palette } from '../theme/palette';

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: palette.bg },
  centered: { flex: 1, justifyContent: 'center', alignItems: 'center', paddingHorizontal: 32 },
  orbTop: { position: 'absolute', top: -70, right: -30, width: 220, height: 220, borderRadius: 110, backgroundColor: 'rgba(255,122,89,0.2)' },
  orbLeft: { position: 'absolute', top: 240, left: -90, width: 240, height: 240, borderRadius: 120, backgroundColor: 'rgba(105,200,255,0.12)' },
  orbBottom: { position: 'absolute', bottom: -110, right: -70, width: 260, height: 260, borderRadius: 130, backgroundColor: 'rgba(89,212,168,0.12)' },
  loadingEyebrow: { color: palette.sand, fontSize: 11, letterSpacing: 2, textTransform: 'uppercase', marginBottom: 10 },
  loadingTitle: { color: palette.text, fontSize: 44, fontWeight: '800', marginBottom: 10 },
  loadingText: { color: palette.muted, fontSize: 15, lineHeight: 22, textAlign: 'center' },
  authScreen: { padding: 22, paddingTop: 32, paddingBottom: 36, gap: 24 },
  authCopy: { gap: 10, marginTop: 18 },
  authEyebrow: { color: palette.sand, fontSize: 11, textTransform: 'uppercase', letterSpacing: 2 },
  authTitle: { color: palette.text, fontSize: 42, lineHeight: 44, fontWeight: '800', maxWidth: 320 },
  authBody: { color: palette.muted, fontSize: 16, lineHeight: 24, maxWidth: 340 },
  authStats: { flexDirection: 'row', gap: 10 },
  authStat: { flex: 1, backgroundColor: 'rgba(255,255,255,0.06)', borderRadius: 22, padding: 16, borderWidth: 1, borderColor: palette.line },
  authStatValue: { color: palette.text, fontSize: 20, fontWeight: '800', marginBottom: 6 },
  authStatLabel: { color: palette.muted, fontSize: 12, textTransform: 'uppercase', letterSpacing: 1 },
  authCard: { backgroundColor: 'rgba(17,26,47,0.92)', borderRadius: 28, padding: 22, borderWidth: 1, borderColor: palette.line, gap: 14 },
  authCardEyebrow: { color: palette.sky, fontSize: 12, textTransform: 'uppercase', letterSpacing: 1.6 },
  authCardTitle: { color: palette.text, fontSize: 28, fontWeight: '800', marginBottom: 4 },
  authPrimary: { backgroundColor: palette.coral, borderRadius: 20, paddingVertical: 16, alignItems: 'center', marginTop: 4 },
  authPrimaryText: { color: palette.bg, fontSize: 15, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1.2 },
  authSwitch: { color: palette.sand, textAlign: 'center', fontSize: 14, lineHeight: 20, marginTop: 4 },
  appShell: { flex: 1, paddingHorizontal: 18, paddingTop: 8, paddingBottom: 18 },
  appHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 18 },
  appDate: { color: palette.muted, fontSize: 13, marginBottom: 4 },
  appTitle: { color: palette.text, fontSize: 30, fontWeight: '800' },
  statusPill: { flexDirection: 'row', alignItems: 'center', gap: 8, paddingHorizontal: 12, paddingVertical: 8, borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.06)', borderWidth: 1, borderColor: palette.line },
  statusDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: palette.mint },
  statusText: { color: palette.text, fontSize: 13, fontWeight: '700' },
  content: { flex: 1 },
  screenContent: { paddingBottom: 24 },
  sectionHeader: { marginBottom: 12, gap: 4 },
  sectionEyebrow: { color: palette.sky, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1.8 },
  sectionTitle: { color: palette.text, fontSize: 24, fontWeight: '800' },
  sectionBody: { color: palette.muted, fontSize: 14, lineHeight: 20 },
  hero: { backgroundColor: 'rgba(17,26,47,0.92)', borderRadius: 30, padding: 22, borderWidth: 1, borderColor: palette.line, marginBottom: 18 },
  heroRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 16, marginBottom: 16 },
  heroCopy: { flex: 1 },
  heroEyebrow: { color: palette.sand, fontSize: 11, textTransform: 'uppercase', letterSpacing: 2, marginBottom: 8 },
  heroTitle: { color: palette.text, fontSize: 32, lineHeight: 35, fontWeight: '800' },
  streakBadge: { backgroundColor: palette.panelAlt, borderRadius: 22, paddingHorizontal: 16, paddingVertical: 12, alignItems: 'center', minWidth: 82 },
  streakLabel: { color: palette.muted, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1.4, marginBottom: 3 },
  streakValue: { color: palette.sand, fontSize: 28, fontWeight: '800' },
  heroText: { color: palette.muted, fontSize: 15, lineHeight: 22, marginBottom: 18 },
  metricBar: { flexDirection: 'row', backgroundColor: 'rgba(255,255,255,0.04)', borderRadius: 20, paddingVertical: 14 },
  metricItem: { flex: 1, alignItems: 'center' },
  metricValue: { fontSize: 22, fontWeight: '800', marginBottom: 3 },
  metricLabel: { color: palette.muted, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1 },
  cardRow: { gap: 12, paddingBottom: 10 },
  highlightCard: { width: 172, borderRadius: 24, padding: 18, backgroundColor: 'rgba(17,26,47,0.92)', borderWidth: 1, borderColor: palette.line },
  highlightAccent: { width: 34, height: 6, borderRadius: 999, marginBottom: 16 },
  highlightTitle: { color: palette.muted, fontSize: 12, textTransform: 'uppercase', letterSpacing: 1.3, marginBottom: 10 },
  highlightValue: { color: palette.text, fontSize: 34, fontWeight: '800', marginBottom: 8 },
  highlightBody: { color: palette.muted, fontSize: 13, lineHeight: 18 },
  panel: { backgroundColor: 'rgba(17,26,47,0.92)', borderRadius: 26, padding: 20, borderWidth: 1, borderColor: palette.line, marginBottom: 16, gap: 14 },
  panelRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  panelTitle: { color: palette.text, fontSize: 18, fontWeight: '700' },
  panelMeta: { color: palette.sand, fontSize: 14, fontWeight: '700' },
  progressTrack: { height: 12, borderRadius: 999, backgroundColor: 'rgba(255,255,255,0.08)', overflow: 'hidden' },
  progressFill: { height: '100%', borderRadius: 999, backgroundColor: palette.sky },
  waterButtons: { flexDirection: 'row', gap: 10 },
  waterButton: { flex: 1, borderRadius: 16, paddingVertical: 12, alignItems: 'center', backgroundColor: palette.panelAlt },
  waterButtonText: { color: palette.text, fontSize: 13, fontWeight: '700' },
  dualRow: { flexDirection: 'row', gap: 12, marginBottom: 18 },
  actionCard: { flex: 1, borderRadius: 24, padding: 18, minHeight: 142, justifyContent: 'space-between', borderWidth: 1, borderColor: palette.line },
  actionWarm: { backgroundColor: 'rgba(255,122,89,0.14)' },
  actionCool: { backgroundColor: 'rgba(89,212,168,0.14)' },
  actionKicker: { color: palette.text, fontSize: 13, textTransform: 'uppercase', letterSpacing: 1.5 },
  actionTitle: { color: palette.text, fontSize: 24, lineHeight: 27, fontWeight: '800' },
  actionBody: { color: palette.muted, fontSize: 13, lineHeight: 18 },
  libraryCard: { width: 186, borderRadius: 24, padding: 18, backgroundColor: 'rgba(17,26,47,0.92)', borderWidth: 1, borderColor: palette.line },
  libraryAccent: { width: 38, height: 8, borderRadius: 999, marginBottom: 16 },
  libraryType: { color: palette.muted, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1.8, marginBottom: 10 },
  libraryName: { color: palette.text, fontSize: 22, lineHeight: 24, fontWeight: '800', marginBottom: 10 },
  libraryMeta: { color: palette.sand, fontSize: 13, marginBottom: 4 },
  listScreen: { flex: 1 },
  primaryButton: { backgroundColor: palette.coral, borderRadius: 20, paddingVertical: 16, alignItems: 'center', marginBottom: 16 },
  primaryButtonText: { color: palette.bg, fontSize: 15, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1.2 },
  listContent: { paddingBottom: 12, gap: 12 },
  entryCard: { flexDirection: 'row', alignItems: 'center', backgroundColor: 'rgba(17,26,47,0.92)', borderRadius: 24, borderWidth: 1, borderColor: palette.line, overflow: 'hidden' },
  entryStripe: { width: 6, alignSelf: 'stretch' },
  entryMain: { flex: 1, paddingHorizontal: 16, paddingVertical: 16 },
  entryActions: { gap: 8, marginRight: 14 },
  entryTitle: { color: palette.text, fontSize: 18, fontWeight: '700', marginBottom: 6 },
  entryMeta: { color: palette.muted, fontSize: 14, marginBottom: 6 },
  entryDate: { color: palette.sky, fontSize: 12, textTransform: 'uppercase', letterSpacing: 1.2 },
  editButton: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 14, backgroundColor: 'rgba(105,200,255,0.12)' },
  editButtonText: { color: palette.sky, fontSize: 12, fontWeight: '700' },
  removeButton: { paddingHorizontal: 12, paddingVertical: 10, borderRadius: 14, backgroundColor: 'rgba(255,157,165,0.12)' },
  removeButtonText: { color: palette.rose, fontSize: 12, fontWeight: '700' },
  emptyCard: { backgroundColor: 'rgba(17,26,47,0.84)', borderRadius: 24, padding: 24, borderWidth: 1, borderColor: palette.line, marginTop: 6 },
  emptyTitle: { color: palette.text, fontSize: 20, fontWeight: '800', marginBottom: 8 },
  emptyBody: { color: palette.muted, fontSize: 14, lineHeight: 21 },
  leaderRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.05)' },
  leaderRank: { width: 34, height: 34, borderRadius: 17, alignItems: 'center', justifyContent: 'center', backgroundColor: palette.panelAlt },
  leaderRankText: { color: palette.sand, fontSize: 12, fontWeight: '800' },
  leaderMain: { flex: 1 },
  leaderName: { color: palette.text, fontSize: 15, fontWeight: '700', marginBottom: 3 },
  leaderNameCurrent: { color: palette.sand },
  leaderMeta: { color: palette.muted, fontSize: 12, lineHeight: 18 },
  leaderScore: { color: palette.coral, fontSize: 16, fontWeight: '800' },
  profileHero: { alignItems: 'center', marginBottom: 18 },
  avatarCircle: { width: 94, height: 94, borderRadius: 47, backgroundColor: 'rgba(255,122,89,0.16)', alignItems: 'center', justifyContent: 'center', borderWidth: 1, borderColor: 'rgba(255,122,89,0.24)', marginBottom: 16 },
  avatarText: { color: palette.text, fontSize: 30, fontWeight: '800' },
  profileName: { color: palette.text, fontSize: 30, fontWeight: '800', marginBottom: 6 },
  profileEmail: { color: palette.muted, fontSize: 14 },
  scoreRow: { flexDirection: 'row', gap: 10, marginBottom: 16 },
  scoreCard: { flex: 1, backgroundColor: 'rgba(17,26,47,0.92)', borderRadius: 22, paddingVertical: 20, alignItems: 'center', borderWidth: 1, borderColor: palette.line },
  scoreValue: { color: palette.text, fontSize: 28, fontWeight: '800', marginBottom: 4 },
  scoreLabel: { color: palette.muted, fontSize: 12, textTransform: 'uppercase', letterSpacing: 1.2 },
  profileBody: { color: palette.muted, fontSize: 14, lineHeight: 22 },
  achievement: { alignSelf: 'flex-start', paddingHorizontal: 14, paddingVertical: 9, borderRadius: 999, backgroundColor: palette.panelAlt, color: palette.sand, fontSize: 12, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1 },
  signOutButton: { backgroundColor: 'rgba(255,157,165,0.14)', borderRadius: 18, paddingVertical: 16, alignItems: 'center' },
  signOutButtonText: { color: palette.rose, fontSize: 15, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
  tabBar: { flexDirection: 'row', gap: 10, padding: 10, borderRadius: 26, backgroundColor: 'rgba(17,26,47,0.94)', borderWidth: 1, borderColor: palette.line, marginTop: 14 },
  tabButton: { flex: 1, borderRadius: 18, paddingVertical: 12, alignItems: 'center', gap: 4 },
  tabButtonActive: { backgroundColor: palette.panelAlt },
  tabCode: { color: palette.muted, fontSize: 10, fontWeight: '700', letterSpacing: 1.4 },
  tabCodeActive: { color: palette.sand },
  tabText: { color: palette.muted, fontSize: 12, fontWeight: '700', textTransform: 'uppercase', letterSpacing: 1 },
  tabTextActive: { color: palette.text },
  modalBackdrop: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(2,6,14,0.72)' },
  modalSheet: { backgroundColor: palette.panel, borderTopLeftRadius: 32, borderTopRightRadius: 32, paddingHorizontal: 22, paddingTop: 20, paddingBottom: 32, borderTopWidth: 1, borderColor: palette.line, gap: 14 },
  modalEyebrow: { color: palette.sand, fontSize: 11, textTransform: 'uppercase', letterSpacing: 1.8 },
  modalTitle: { color: palette.text, fontSize: 30, fontWeight: '800' },
  input: { backgroundColor: 'rgba(255,255,255,0.05)', borderRadius: 18, paddingHorizontal: 16, paddingVertical: 15, color: palette.text, fontSize: 16, borderWidth: 1, borderColor: palette.line },
  segmentRow: { flexDirection: 'row', gap: 10 },
  segmentButton: { flex: 1, borderRadius: 16, paddingVertical: 13, alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.04)', borderWidth: 1, borderColor: palette.line },
  segmentButtonActive: { backgroundColor: palette.coral, borderColor: palette.coral },
  segmentText: { color: palette.muted, fontSize: 12, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
  segmentTextActive: { color: palette.bg },
  dualInputRow: { flexDirection: 'row', gap: 12 },
  half: { flex: 1 },
  modalActions: { flexDirection: 'row', gap: 12, marginTop: 4 },
  modalGhost: { flex: 1, borderRadius: 18, paddingVertical: 16, alignItems: 'center', backgroundColor: 'rgba(255,255,255,0.06)' },
  modalGhostText: { color: palette.text, fontSize: 14, fontWeight: '700' },
  modalPrimary: { flex: 1, borderRadius: 18, paddingVertical: 16, alignItems: 'center', backgroundColor: palette.coral },
  modalPrimaryText: { color: palette.bg, fontSize: 14, fontWeight: '800', textTransform: 'uppercase', letterSpacing: 1 },
});
